# Generated by Django 2.0.3 on 2018-03-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campus', models.IntegerField()),
                ('cam_nombre', models.CharField(max_length=50)),
                ('cam_descripcion', models.CharField(max_length=50)),
                ('cam_longitud', models.CharField(max_length=50)),
                ('cam_latitud', models.CharField(max_length=50)),
            ],
        ),
    ]
