# Generated by Django 2.0.3 on 2018-03-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignaturasresumen',
            fields=[
                ('id_asignaturar', models.AutoField(primary_key=True, serialize=False)),
                ('asi_aprobadas', models.IntegerField()),
                ('asi_reprobados', models.IntegerField()),
                ('asi_anulados', models.IntegerField()),
                ('asi_retiros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='carreras',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estudiantesresumen',
            fields=[
                ('id_estudianter', models.AutoField(primary_key=True, serialize=False)),
                ('est_inscritos', models.IntegerField()),
                ('est_prematriculados', models.IntegerField()),
                ('est_matriculados', models.IntegerField()),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.carreras')),
            ],
        ),
        migrations.CreateModel(
            name='periodoslectivos',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('per_descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='campus',
            name='id',
        ),
        migrations.AlterField(
            model_name='campus',
            name='id_campus',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='estudiantesresumen',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.periodoslectivos'),
        ),
        migrations.AddField(
            model_name='carreras',
            name='id_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.campus'),
        ),
        migrations.AddField(
            model_name='asignaturasresumen',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.carreras'),
        ),
        migrations.AddField(
            model_name='asignaturasresumen',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.periodoslectivos'),
        ),
    ]
